name: Build and deploy static site

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "README.md"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Hugo
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.131.0"
          extended: true

      # Build the Site
      - name: Build site with Hugo
        run: hugo --minify

      - name: Add SSH key for rsync
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to Tailnet
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          ping: ${{ secrets.SERVER_SSH_HOST }}

      - name: Verify server host key fingerprint
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_SSH_HOST }} > ~/.ssh/server_host_key
          ssh-keygen -lf ~/.ssh/server_host_key | grep -F "${{ secrets.SERVER_SSH_FINGERPRINT }}"
          cat ~/.ssh/server_host_key >> ~/.ssh/known_hosts

      - name: Copy built site to server
        run: rsync -av --delete public/ ${{ secrets.SERVER_SSH_USERNAME }}@${{ secrets.SERVER_SSH_HOST }}:/var/www/pyrah.us/
